apiVersion: v1
kind: Service
metadata:
  name: cohesive-service
spec:
  type: LoadBalancer
  ports:
    -  targetPort: 80
       port: 80
       nodePort: 30008
  selector:
    app: cohesive
    tier: frontend
