apiVersion: v1
kind: ReplicationController
metadata:
  name: cohesive-rc
  labels:
    app: cohesive
    type: front-end
spec:
  replicas: 2
  selector:
    app: cohesive
  template:
    metadata:
      name: ngix
      labels:
        app: cohesive
    spec:
      containers:
        - name: nginx
          image: nginx
