# All the variables for install_kubeadmin playbook.
ansible_python_interpreter: /usr/bin/python3
ansible_user: cloud_user
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

sysctl_config:
      net.ipv4.ip_forward: 1
      net.ipv4.conf.all.forwarding: 1
      net.ipv6.conf.all.forwarding: 1
      net.bridge.bridge-nf-call-ip6tables: 1
      net.bridge.bridge-nf-call-iptables: 1