# Example config-file
apiVersion: apps/v1
kind: Deployment
metadata:  # Deployment metadata
  name: mongodb-deployment
	labels:
    app: mongodb
spec:      # Deployment Specifications
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata: # pod specific metadata
      labels:
        app: mongodb
    spec:    # pod specific specifications
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        - name: SOME_RESOURCE_REFRENCING_A_VALUE_FROM_A_CONFIG_MAP
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url

---
apiVersion: v1
kind: Service
metadata:  
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---
apiVersion: v1
kind: Secret
metadata:  
  name: mongodb-secret
type: Opaque
data:
    mongo-root-username: "${base64_encoded_data}"
    mongo-root-password: "${base64_encoded_data}"

---
apiVersion: v1
kind: ConfigMap
metadata:  
  name: mongodb-configmap
data:
    database_url: mongodb-service