apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    tier: frontend
    app: ngix
spec:
  replicas: 4
  template:
    metadata:
      name: ngix-pod
      labels:
        app: ngix
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
  selector:     # Use to search for other pods that match the lable and are off the same template.
    matchLabels:  # create any key/value pair to match othe PODs that should be control by this replicaset.
      app: ngix
